-- Создание таблицы участников гильдии
CREATE TABLE guild_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    balance BIGINT NOT NULL DEFAULT 0,
    last_voice_check_at TIMESTAMP WITH TIME ZONE,
    user_name VARCHAR(255),
    guild_name VARCHAR(255),
    CONSTRAINT uk_guild_user UNIQUE (guild_id, user_id)
);

-- Создание таблицы транзакций
CREATE TABLE points_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    amount INTEGER NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transaction_member FOREIGN KEY (member_id) REFERENCES guild_members(id)
);

-- Индекс для оптимизации поиска транзакций по участнику
CREATE INDEX idx_points_transactions_member_id ON points_transactions(member_id);
