-- Ссылка на объект, породивший движение средств (например, id пари)
ALTER TABLE points_transactions ADD COLUMN reference_id BIGINT;

CREATE INDEX idx_points_transactions_reference_id ON points_transactions(reference_id);

-- Пари (пользовательские ставки в стиле Twitch Predictions)
CREATE TABLE paris (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id VARCHAR(255) NOT NULL,
    author_id VARCHAR(255) NOT NULL,
    author_name VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    winning_option BOOLEAN,
    channel_id VARCHAR(255),
    message_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    settled_at TIMESTAMP WITH TIME ZONE
);

-- Выборка пари, ожидающих расчета (используется восстановительным планировщиком)
CREATE INDEX idx_paris_status ON paris(status);

-- Ставка участника в пари
CREATE TABLE pari_bets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pari_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    bet_option BOOLEAN NOT NULL,
    amount BIGINT NOT NULL,
    settled BOOLEAN NOT NULL DEFAULT FALSE,
    payout BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    settled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_pari_bet_pari FOREIGN KEY (pari_id) REFERENCES paris(id),
    CONSTRAINT fk_pari_bet_member FOREIGN KEY (member_id) REFERENCES guild_members(id),
    CONSTRAINT uk_pari_bet_pari_member UNIQUE (pari_id, member_id),
    CONSTRAINT ck_pari_bet_amount_positive CHECK (amount > 0)
);

-- Индекс для батч-обработки невыплаченных ставок
CREATE INDEX idx_pari_bets_pari_settled ON pari_bets(pari_id, settled);

-- Баланс участника не может уйти в минус
ALTER TABLE guild_members ADD CONSTRAINT ck_guild_members_balance_non_negative CHECK (balance >= 0) NOT VALID;
